export class Hello {
    get(locale: string): string {
        const all = Hello.all as any;
        return all[(locale || "").toLowerCase()] || all["a1"];
    }

    private static readonly all = {
        "a1": "Hello {name}",
        "a2": "Hello {name}",
        "ad": "Hola {name}",
        "ae": "Marhaba {name}",
        "af": "Senga yai {name}",
        "ag": "Hello {name}",
        "ai": "Hello {name}",
        "al": "Tungjatjeta {name}",
        "am": "Barev {name}",
        "an": "Kon ta bai {name}",
        "ao": "Olá {name}",
        "ap": "Hello {name}",
        "aq": "Hello {name}",
        "ar": "Hola {name}",
        "as": "Hello {name}",
        "at": "Hallo {name}",
        "au": "Hello {name}",
        "aw": "Kon ta bai {name}",
        "ax": "Hello {name}",
        "az": "Salam {name}",
        "ba": "Zdravo {name}",
        "bb": "Hello {name}",
        "bd": "Namaskar {name}",
        "be": "Hallo {name}",
        "bf": "Bonjour {name}",
        "bg": "Zdravei {name}",
        "bh": "Marhaba {name}",
        "bi": "Bonjour {name}",
        "bj": "Bonjour {name}",
        "bm": "Hello {name}",
        "bn": "Selamat {name}",
        "bo": "Hola {name}",
        "br": "Olá {name}",
        "bs": "Hello {name}",
        "bt": "Kuzu zangpo {name}",
        "bv": "Hello {name}",
        "bw": "Dumela {name}",
        "by": "Вітаю {name}",
        "bz": "Hello {name}",
        "ca": "Hello {name}",
        "cd": "Bonjour {name}",
        "cf": "Bonjour {name}",
        "cg": "Bonjour {name}",
        "ch": "Hallo {name}",
        "ci": "Bonjour {name}",
        "ck": "Kia orana {name}",
        "cl": "Hola {name}",
        "cm": "Hello {name}",
        "cn": "\u4f60\u597d {name}",
        "co": "Hola {name}",
        "cr": "Hola {name}",
        "cu": "Hola {name}",
        "cv": "Olá {name}",
        "cy": "\u0393\u03b5\u03b9\u03b1 \u03c3\u03bf\u03c5 {name}",
        "cz": "Dobrý den {name}",
        "de": "Hallo {name}",
        "dj": "Marhaba {name}",
        "dk": "Hej {name}",
        "dm": "Hello {name}",
        "do": "Hola {name}",
        "dz": "Marhaba {name}",
        "ec": "Hola {name}",
        "ee": "Tervist {name}",
        "eg": "Marhaba {name}",
        "er": "Marhaba {name}",
        "es": "Hola {name}",
        "et": "Teanastëllën {name}",
        "eu": "Hello {name}",
        "fi": "Moi {name}",
        "fj": "Hello {name}",
        "fk": "Hello {name}",
        "fm": "Hello {name}",
        "fo": "Hallo {name}",
        "fr": "Bonjour {name}",
        "ga": "Bonjour {name}",
        "gb": "Hello {name}",
        "gd": "Hello {name}",
        "ge": "Gamardjobat {name}",
        "gf": "Bonjour {name}",
        "gg": "Hello {name}",
        "gh": "Hello {name}",
        "gi": "Hello {name}",
        "gl": "Aluu {name}",
        "gm": "Hello {name}",
        "gn": "Bonjour {name}",
        "gp": "Hello {name}",
        "gq": "Hola {name}",
        "gr": "\u0393\u03b5\u03b9\u03b1 \u03c3\u03bf\u03c5 {name}",
        "gt": "Hola {name}",
        "gu": "Hello {name}",
        "gw": "Olá {name}",
        "gy": "Hello {name}",
        "hk": "\u4f60\u597d {name}",
        "hn": "HHola {name}",
        "hr": "Bok {name}",
        "ht": "Bonjour {name}",
        "hu": "Jó napot {name}",
        "id": "Selamat {name}",
        "ie": "Haileo {name}",
        "il": "Shalom {name}",
        "im": "Hello {name}",
        "in": "\u0928\u092e\u0938\u094d\u0924\u0947 {name}",
        "io": "Hello {name}",
        "iq": "Marhaba {name}",
        "ir": "Salâm {name}",
        "is": "Góðan daginn {name}",
        "it": "Buon giorno {name}",
        "je": "Hello {name}",
        "jm": "Hello {name}",
        "jo": "Marhaba {name}",
        "jp": "\u3053\u3093\u306b\u3061\u306f {name}",
        "ke": "Habari {name}",
        "kg": "Kandisiz {name}",
        "kh": "Sua s''dei {name}",
        "ki": "Mauri {name}",
        "km": "Bariza djioni {name}",
        "kn": "Hello {name}",
        "kp": "\uc548\ub155\ud558\uc138\uc694 {name}",
        "kr": "\uc548\ub155\ud558\uc138\uc694 {name}",
        "kw": "Marhaba {name}",
        "ky": "Hello {name}",
        "kz": "Salam {name}",
        "la": "Sabaidee {name}",
        "lb": "Marhaba {name}",
        "lc": "Hello {name}",
        "li": "Hallo {name}",
        "lk": "A`yubowan {name}",
        "lr": "Hello {name}",
        "ls": "Hello {name}",
        "lt": "Laba diena {name}",
        "lu": "Moïen {name}",
        "lv": "Sveiki {name}",
        "ly": "Marhaba {name}",
        "ma": "Marhaba {name}",
        "mc": "Bonjour {name}",
        "md": "Salut {name}",
        "me": "Zdravo {name}",
        "mg": "Manao ahoana {name}",
        "mh": "Yokwe {name}",
        "mk": "\u0417\u0434\u0440\u0430\u0432\u043e {name}",
        "ml": "Bonjour {name}",
        "mm": "Mingalarba {name}",
        "mn": "Sain baina uu {name}",
        "mo": "\u4f60\u597d {name}",
        "mp": "Hello {name}",
        "mq": "Hello {name}",
        "mr": "Marhaba {name}",
        "ms": "Hello {name}",
        "mt": "Bongu {name}",
        "mu": "Hello {name}",
        "mv": "Kihineth {name}",
        "mw": "Muribwanji {name}",
        "mx": "Hola {name}",
        "my": "Selamat {name}",
        "mz": "Olá {name}",
        "na": "Hello {name}",
        "nc": "Bozo {name}",
        "ne": "Bonjour {name}",
        "nf": "Whataway {name}",
        "ng": "Hello {name}",
        "ni": "Hola {name}",
        "nl": "Hallo {name}",
        "no": "Hallo {name}",
        "np": "Namaste {name}",
        "nr": "Hello {name}",
        "nu": "Faka lofa lahi atu {name}",
        "nz": "Hello {name}",
        "om": "Marhaba {name}",
        "pa": "Hola {name}",
        "pe": "Hola {name}",
        "pf": "Bonjour {name}",
        "pg": "Hello {name}",
        "ph": "Halo {name}",
        "pk": "Adaab {name}",
        "pl": "Dzień dobry {name}",
        "pm": "Hello {name}",
        "pr": "Hola {name}",
        "ps": "Marhaba {name}",
        "pt": "Olá {name}",
        "pw": "Alii {name}",
        "py": "Hola {name}",
        "qa": "Marhaba {name}",
        "re": "Hello {name}",
        "ro": "Salut {name}",
        "rs": "Zdravo {name}",
        "ru": "\u0417\u0434\u0440\u0430\u0432\u0441\u0442\u0432\u0443\u0439\u0442\u0435 {name}",
        "rw": "Hello {name}",
        "sa": "Marhaba {name}",
        "sb": "Hello {name}",
        "sc": "Hello {name}",
        "sd": "Marhaba {name}",
        "se": "God dag {name}",
        "sg": "Selamat {name}",
        "si": "Živijo {name}",
        "sk": "Dobrý deň {name}",
        "sl": "Hello {name}",
        "sm": "Buon giorno {name}",
        "sn": "Bonjour {name}",
        "so": "Maalim wanaqsan {name}",
        "sr": "Hallo {name}",
        "st": "Hello {name}",
        "sv": "Hola {name}",
        "sy": "Marhaba {name}",
        "sz": "Hello {name}",
        "tc": "Hello {name}",
        "td": "Marhaba {name}",
        "tg": "Bonjour {name}",
        "th": "Sawatdi {name}",
        "tj": "Salom {name}",
        "tk": "Taloha {name}",
        "tm": "Salam {name}",
        "tn": "Marhaba {name}",
        "to": "Malo e lelei {name}",
        "tr": "Merhaba {name}",
        "tt": "Hello {name}",
        "tv": "Talofa {name}",
        "tw": "\u4f60\u597d {name}",
        "tz": "Habari {name}",
        "ua": "Pryvit {name}",
        "ug": "Habari {name}",
        "uk": "Hello {name}",
        "um": "Hello {name}",
        "us": "Hello {name}",
        "uy": "Hola {name}",
        "uz": "Salom {name}",
        "va": "Buon giorno {name}",
        "vc": "Hello {name}",
        "ve": "Hola {name}",
        "vg": "Hello {name}",
        "vi": "Hello {name}",
        "vn": "Chào {name}",
        "vu": "Halo {name}",
        "wf": "Malo le kataki {name}",
        "ws": "Talofa {name}",
        "ye": "Marhaba {name}",
        "yt": "Hello {name}",
        "za": "Hello {name}",
        "zm": "Hello {name}",
        "zw": "Hello {name}",
        "rd": "Hello {name}"
    };
}